github: [sardorbekdev]
patreon: sardorbekdev
open_collective: sardorbekdev
ko_fi: sardorbekdev
community_bridge: cloud-foundry
liberapay: sardorbekdev
issuehunt: sardorbekdev
lfx_crowdfunding: cloud-foundry
polar: sardorbekdev
buy_me_a_coffee: sardorbekdev
thanks_dev: sardorbekdev
custom:
  - https://t.me/sardorbekdev
  - https://paypal.me/sardorbekdev
  - https://mywebsite.com/donate
  - https://uzcard.uz/payme-link
